# DESCRIPTION: On push events to monitored patterns, install dependencies, execute unit tests,
# apply linting, build solution, deploy solution, and notify Fireteam and ChatOps channels.

# NOTES: This workflow ignores the infrastructure stack changes and is targeted at deploying
# code. Will only run on push events that INCLUDE AT LEAST ONE file outside the paths-ignore
# directory at the root of the repository.

name: CD code / On push to develop/main

on:
  workflow_dispatch: # Need to test the manual trigger. What does environment mean and map to?
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        type: choice
        options:
          - develop
          - test
          - prod
        default: 'develop'
  push:
    branches:
      - main
      - develop
      - feature/boiler-plate

jobs:
  buildTestAndDeploy:
    name: Build, test and deploy
    runs-on: ubuntu-latest

    environment: >-
      ${{
        github.event_name == 'workflow_dispatch' &&
          format('Arcadia {0}',
            startsWith(inputs.environment, 'p') && 'Prod' ||
            startsWith(inputs.environment, 't') && 'Test' ||
            'Develop'
          ) ||
        github.ref_name == 'main' &&
          'Arcadia Prod' ||
        github.ref_name == 'develop' &&
          'Arcadia Test' ||
        'Arcadia Develop'
      }}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        env:
          ARCADIA_DEVELOP_AWS_KEY: ${{ secrets.ARCADIA_DEVELOP_AWS_KEY }}
          ARCADIA_DEVELOP_AWS_SECRET: ${{ secrets.ARCADIA_DEVELOP_AWS_SECRET }}

          # ARCADIA_TEST_AWS_KEY: ${{ secrets.ARCADIA_TEST_AWS_KEY }}
          # ARCADIA_TEST_AWS_SECRET: ${{ secrets.ARCADIA_TEST_AWS_SECRET }}

          # ARCADIA_PROD_AWS_KEY: ${{ secrets.ARCADIA_PROD_AWS_KEY }}
          # ARCADIA_PROD_AWS_SECRET: ${{ secrets.ARCADIA_PROD_AWS_SECRET }}
        run: |
          mkdir ~/.aws && touch ~/.aws/credentials
          cat <<EOL >> ~/.aws/credentials
          [default]
          aws_access_key_id=nil
          aws_secret_access_key=nil

          [arcadia-develop]
          aws_access_key_id=$ARCADIA_DEVELOP_AWS_KEY
          aws_secret_access_key=$ARCADIA_DEVELOP_AWS_SECRET

          [arcadia-test]
          aws_access_key_id=$ARCADIA_TEST_AWS_KEY
          aws_secret_access_key=$ARCADIA_TEST_AWS_SECRET

          [arcadia-prod]
          aws_access_key_id=$ARCADIA_PROD_AWS_KEY
          aws_secret_access_key=$ARCADIA_PROD_AWS_SECRET
          EOL

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm ci && aws --version

      - name: Build UI solution (Arcadia Develop)
        if: success() && github.ref == 'refs/heads/feature/boiler-plate'
        run: |
          npm run build:test

      - name: Build UI solution (Arcadia Test)
        if: success() && github.ref == 'refs/heads/develop'
        run: |
          npm run build:test

      - name: Build UI solution (Arcadia Prod)
        if: success() && github.ref == 'refs/heads/main'
        run: |
          npm run build:prod
      
      - name: Deploy UI solution to S3 (Arcadia Test)
        if: success() && github.ref == 'refs/heads/feature/boiler-plate'
        env:
          ACCOUNT: arcadia
          CBG_ENVIRONMENT: develop
          REGION: ap-south-1
        run: |
          echo "Profile: $ACCOUNT-$CBG_ENVIRONMENT"
          echo "Region: $REGION"
          echo "Bucket: ${ACCOUNT}-${CBG_ENVIRONMENT}-sites"
          aws s3 sync --profile "$ACCOUNT-$CBG_ENVIRONMENT" \
            --region "$REGION" \
            ./dist/nexusgate-pbmui/browser \
            s3://nexusgate-pbmui --delete --sse

      - name: Deploy UI solution to S3 (Arcadia Prod)
        if: success() && github.ref == 'refs/heads/main'
        env:
          ACCOUNT: arcadia
          CBG_ENVIRONMENT: prod
          REGION: us-west-2
        run: |
          aws s3 sync --profile "$ACCOUNT-$CBG_ENVIRONMENT" \
            --region "$REGION" \
            ./dist/portal/ \
            s3://${ACCOUNT}-${CBG_ENVIRONMENT}-sites --delete --sse

      - name: Create CloudFront invalidation
        env:
          AWS_REGION: ap-south-1
          CBG_ACCOUNT_SET: arcadia
          CBG_ENVIRONMENT: develop
        run: |
          DISTRIBUTION_ID=$(aws cloudfront list-distributions --profile "$CBG_ACCOUNT_SET-$CBG_ENVIRONMENT" \
            --query "DistributionList.Items[?Origins.Items[?DomainName!=null && contains(DomainName, 'nexusgate-pbmui.S3.${AWS_REGION}.amazonaws.com')]].Id" \
            --output text)
          
          echo "DISTRIBUTION_ID: " $DISTRIBUTION_ID
          if [ -z "$DISTRIBUTION_ID" ]; then
            echo "No matching CloudFront distribution found"
            exit 1
          fi
          
          aws cloudfront create-invalidation --profile "$CBG_ACCOUNT_SET-$CBG_ENVIRONMENT" \
            --distribution-id $DISTRIBUTION_ID \
            --paths "/index.html"


      - name: OWASP Zap Scan (Arcadia Prod)
        if: success() && github.ref == 'refs/heads/main'
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: https://nexusgate-pbmui.cbgapps.io

      - name: Compile build message for logs and notifications
        if: always()
        id: build_message
        env:
          JOB_STATUS: ${{ job.status }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_EVENT: ${{ github.event_name }}
          GITHUB_JOB: ${{ github.job }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          GITHUB_RUN_NO: ${{ github.run_number }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          echo ::set-output name=friendly::"**SERVICE:** CBG Arcadia > Members | **REPO:** $GITHUB_REPOSITORY | **REF:** $GITHUB_REF | **HEAD\_REF:** $GITHUB_HEAD_REF | **BASE\_REF:** $GITHUB_BASE_REF | **EVENT:** ${GITHUB_EVENT//_} | **MESSAGE:** Job _${GITHUB_JOB}_ completed in workflow _${GITHUB_WORKFLOW}_ for run _${GITHUB_RUN_NO}_ by _${GITHUB_ACTOR}_ with status of _${JOB_STATUS}_"

          echo ::set-output name=json::\''{"service": "CBG Arcadia > Members", "jobStatus": "'"$JOB_STATUS"'", "repository": "'"$GITHUB_REPOSITORY"'", "githubRef": "'"$GITHUB_REF"'", "githubHeadRef": "'"$GITHUB_HEAD_REF"'", "githubBaseRef": "'"$GITHUB_BASE_REF"'", "githubJob": "'"$GITHUB_JOB"'", "githubWorkflow": "'"$GITHUB_WORKFLOW"'", "githubRunNo": "'"$GITHUB_RUN_NO"'", "githubActor": "'"$GITHUB_ACTOR"'", "markdown": "'"Job _${GITHUB_JOB}_ completed in workflow _${GITHUB_WORKFLOW}_ for run _${GITHUB_RUN_NO}_ by _${GITHUB_ACTOR}_ with status of _${JOB_STATUS}_"'"}'\'

      # - name: Notify Slack
      #   if: always()
      #   uses: slackapi/slack-github-action@v2.0.0
      #   with:
      #     webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     webhook-type: incoming-webhook
      #     payload: |
      #       text: >-
      #         ${{ job.status == 'success' &&
      #             ':white_check_mark: Deployment successful' ||
      #             ':x: Deployment failed'
      #         }} for ${{ github.repository }} to ${{ github.ref_name }}
      #       blocks:
      #         - type: section
      #           text:
      #             type: mrkdwn
      #             text: >-
      #               ${{ job.status == 'success' &&
      #                   ':white_check_mark: Deployment successful' ||
      #                   ':x: Deployment failed'
      #               }} for ${{ github.repository }} to ${{ github.ref_name }}
      #         - type: section
      #           text:
      #             type: mrkdwn
      #             text: >-
      #               ${{ job.status == 'success' &&
      #                   'UI has been successfully deployed.' ||
      #                   'The deployment process has failed.
      #                   Please check the GitHub Actions logs for details.'
      #               }}
